[package]
name = "lepton_jpeg_python"
version = "0.5.5"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
lepton_jpeg = { path = "../lib" }
rayon = "1"

